apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: podinfo
  namespace: dev
spec:
  name: podinfo
  namespace: podinfo
  git:
    folder: podinfo
    ref: main
  repositoryRef:
    kind: GitRepository
    name: demo
    namespace: infra
  helm:
    values:
      image:
        tag: 6.5.3 # VERSION
  clusterRef:
    kind: Cluster
    name: k3s-test # change this to the appropriate name for your main test cluster
    namespace: infra