apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: prod
spec:
  name: pipeline-prod
  namespace: prod
  git:
    folder: prod
    ref: main
  repositoryRef:
    kind: GitRepository
    name: demo
    namespace: infra
  clusterRef:
    kind: Cluster
    name: mgmt # change this to the appropriate name for your main test cluster
    namespace: infra